
GET http://localhost:3000/login
Content-Type: application/json

{
    "userId":"102",
    "password":"hi"
}

###

POST http://localhost:3000/hostEmail
Content-Type: application/json

{
    "hostName":"nikk@gmail.com",
    "distributionList":["thomas@gmail.com","camille@gmail.com"]
}
###

POST http://localhost:3000/hostEmail
Content-Type: application/json

{
    "hostName":"contact.reesoi@gmail.com",
    "distributionList":["niharikap219@gmail.com","hi@gmail.com"]
}

###

GET http://localhost:3000/distributionList
Content-Type: application/json

{
    "hostName":"contact.reesoi@gmail.com"
}

###

PUT http://localhost:3000/customers/scott.morton@yahoo.com/ryan.dupont@gmail.com

###

PUT http://localhost:3000/hostNames/ryan.dupont@gmail.com/mercy.pote@gmail.com

###
DELETE http://localhost:3000/record/contact.reesoi@gmail.com

###

PUT http://localhost:3000/newsletter
Content-Type: application/json

{
    "userCreds":{
        "user": "contact.reesoi@gmail.com",
        "pass": "Soiree219"
    },
    "text":"./seraphina.txt"
}

###

DELETE http://localhost:3000/customer/contact.reesoi@gmail.com/hi@gmail.com